# version: '3'
services:
  db:
    image: postgres:16
    container_name: postgres16_rails
    volumes:
      - postgres16:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
  web:
    container_name: web_rails
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle update && bundle exec rails s -b '0.0.0.0'"  # 変更箇所
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_rails
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
  nginx:
    image: nginx
    container_name: nginx_rails
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  postgres16:
  pgadmin:
